config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
  get 'results', to: 'pages#create', as: "result"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/meal.rb
class Meal < ApplicationRecord
end

app/models/transport.rb
class Transport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meal_controller.rb
class MealController < ApplicationController
  def index
    @Meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:meal_id])
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new
  end

  def edit
  end

  def update
  end

  def delete
  end

  private

  def meal_params
    params.require(:meal).permit(:user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def create
    food = Food.where(name: params[:diet]["food"])[0]
    emissions_per_kg = food.emissions
    @one_year_emissions = params[:diet]["amount"].to_f * emissions_per_kg.to_f * food.average_amount.to_f

    car = Transport.where(name: 'Car')[0]
    train = Transport.where(name: 'Train')[0]
    domestic_flight = Transport.where(name: 'Flight (Domestic)')[0]
    short_flight = Transport.where(name: 'Flight (Short Haul)')[0]
    long_flight = Transport.where(name: 'Flight (Long Haul)')[0]

    # how far you can travel for the same emissions by different means
    @car_km = @one_year_emissions / car.emissions.to_f
    @train_km = @one_year_emissions / train.emissions.to_f
    @domestic_flight_km = @one_year_emissions / domestic_flight.emissions.to_f
    @short_flight_km = @one_year_emissions / short_flight.emissions.to_f
    @long_flight_km = @one_year_emissions / long_flight.emissions.to_f
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meal_helper.rb
module MealHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EatGreen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </body>
</html>

app/views/pages/create.html.erb
<div class="home-banner">
  <div class="results-container">
    <h1 class="mb-3"><%= @one_year_emissions.floor %>kg of CO2 per year</h1>
    <h3>The same amount of CO2 is produced by... </h3>
    <div class="travel-figures mt-4">
      <div class="travel-container m-4">
        <p>...travelling around <br> <%= @car_km.floor %>km <br> by car</p>
      </div>
      <div class="travel-container m-4">
        <p>...travelling around <br> <%= @train_km.floor %>km <br> by train</p>
      </div>
      <div class="travel-container m-4">
        <p>...travelling around <br> <%= @domestic_flight_km.floor %>km <br> on a domestic flight</p>
      </div>
      <div class="travel-container m-4">
        <p>...travelling around <br> <%= @short_flight_km.floor %>km <br> by short haul flight</p>
      </div>
      <div class="travel-container m-4">
        <p>...travelling around <br> <%= @long_flight_km.floor %>km <br> by long haul flight</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/create.js.erb
const searchResults = () => {
  const searchButton = document.querySelector(".btn-search");
  const resultsOfSearch = document.querySelector('.results-of-search');
  const food = document.querySelector('#diet_food');

  const results = (event) => {
    console.log(food.value)
    resultsOfSearch.insertAdjacentHTML("beforeend", `<h1>food </h1>`);
  };

  searchButton.addEventListener("click", results);
};

export { searchResults };

app/views/pages/home.html.erb
<div class="home-banner">
  <div class="home-container">

    <h1>Welcome to EatGreen</h1>

    <p>Fill in the form below in order to see how your diet affects the planet!</p>

    <div class="">
      <%= simple_form_for :diet, url: result_path, method: "GET" do |f| %>
        <div class="p-3">
          <div class="home-form inline-block d-flex">
            <%= f.input :food, collection: ["Beef", "Lamb", "Cheese", "Farmed Salmon", "Turkey", "Chicken", "Canned Tuna", "Eggs", "Potatoes", "Rice", "Peanut Butter", "Nuts", "Yogurt", "Broccoli", "Tofu", "Dry Beans", "Milk (2%)", "Tomatoes", "Lentils"] %><%= f.input :amount, collection: [["Once a month", 12], ["Once a week", 52], ["3 times a week", 156], ["Once a day", 365], ["Every meal", 1095]] %>

          <!-- :amount tracks the amount of times the specific food is eaten in a year -->
          </div>

        <%= f.button :submit, "Search", class: "btn btn-dark btn-search" %>

        </div>

      <% end %>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/home.html", class: "navbar-brand" do %>
    EG
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>